# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45be7492eee3f865a4ff72876947ac83f62e8e6ab73f2454d5d95fc6dea7844126f137ba4246c9b88ad97cfa18ede394eebd4fca700d01f5b6a81d0a1d510562

test:
  secret_key_base: 2002010bc5dc5b7d6665e99c71e2622a0526e3bcc2b698efab64ed9726c4f1edd8287f6f337591d6f5c7774b3785b27033f7b3df9a4103dd24b028b478e19ad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
